aws_config_ini: null
buckets:
- test
cleanup_interval: 7
log_format: null
log_level: INFO
log_traceback: true
s3_access_key_id: test
s3_endpoint_url: http://localstack:4566
s3_secret_access_key: '**********'
s3_session_token: null
service_instance_id: '001'
service_name: muc
